### ISSUE TITLE
Bar chart implementation needs to change

### ISSUE THREAD

**Issue by swethakan** [CMU-Vis-2021/assignment-3-environment-viz#10]
Bars are being implemented overtop each other. 

We need to re-format the data before we send it into the updateBarChart() function or at the very beginning of it.
Basically, after we filter for the year, we also need to combine all the categories and they're sizes into a different data variable. 

So if for one year, we have 3 fireworks caused fires and each of them were 100acres, the new data set should sshow only 1 firework fire that's 300acres.

**Comment by katelyn98** [comment]
implemented
